# Calculate GDP growth of regions in Finland

Data source: Statistic Finland

Table: 12bc -- Gross domestic product per capita by area, annually, 2000-2020

Link: https://pxdata.stat.fi/PxWeb/pxweb/en/StatFin/StatFin__altp/statfin_altp_pxt_12bc.px/table/tableViewLayout1/

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create the base with region column DataFrame
base_df = pd.read_csv('../data/Indices/population_density_index.csv')
base_df = base_df[['Region code', 'Region name (en)', 'Region name (fi)']].copy()

base_df

   Region code      Region name (en)   Region name (fi)
0         MK01               Uusimaa            Uusimaa
1         MK02     Southwest Finland    Varsinais-Suomi
2         MK04             Satakunta          Satakunta
3         MK05            Kanta-Häme         Kanta-Häme
4         MK06             Pirkanmaa          Pirkanmaa
5         MK07           Päijät-Häme        Päijät-Häme
6         MK08           Kymenlaakso        Kymenlaakso
7         MK09         South Karelia      Etelä-Karjala
8         MK10            South Savo         Etelä-Savo
9         MK11            North Savo       Pohjois-Savo
10        MK12         North Karelia    Pohjois-Karjala
11        MK13       Central Finland        Keski-Suomi
12        MK14    South Ostrobothnia    Etelä-Pohjanmaa
13        MK15          Ostrobothnia          Pohjanmaa
14        MK16  Central Ostrobothnia    Keski-Pohjanmaa
15        MK17    North Ostrobothnia  Pohjois-Pohjanmaa
16        MK18                Kainuu             Kainuu
17        MK19               Lapland              Lappi
18        MK21                 Åland         Ahvenanmaa

In [3]:
import requests
import json

# Define the URL and JSON query
url = "https://pxdata.stat.fi:443/PxWeb/api/v1/en/StatFin/altp/statfin_altp_pxt_12bc.px"
query = {
  "query": [
    {
      "code": "Alue",
      "selection": {
        "filter": "item",
        "values": [
          "MK01",
          "MK02",
          "MK04",
          "MK05",
          "MK06",
          "MK07",
          "MK08",
          "MK09",
          "MK10",
          "MK11",
          "MK12",
          "MK13",
          "MK14",
          "MK15",
          "MK16",
          "MK17",
          "MK18",
          "MK19",
          "MK21"
        ]
      }
    },
    {
      "code": "Vuosi",
      "selection": {
        "filter": "item",
        "values": [
          "2016",
          "2017",
          "2018",
          "2019",
          "2020"
        ]
      }
    },
    {
      "code": "Tiedot",
      "selection": {
        "filter": "item",
        "values": [
          "GDPcap",
          "EP"
        ]
      }
    }
  ],
  "response": {
    "format": "json-stat2"
  }
}

# Send the POST request
response = requests.post(url, json=query)

# Check the response status and content
if response.status_code == 200:
    json_data = response.json()
else:
    print("Request failed with status code:", response.status_code)

json_data

{'class': 'dataset',
 'label': 'Gross domestic product per capita by area, annually by Area, Year and Information',
 'source': 'Statistics Finland, regional account',
 'updated': '2022-12-01T06:00:00Z',
 'id': ['Alue', 'Vuosi', 'Tiedot'],
 'size': [19, 5, 2],
 'dimension': {'Alue': {'extension': {'show': 'value'},
   'label': 'Area',
   'category': {'index': {'MK01': 0,
     'MK02': 1,
     'MK04': 2,
     'MK05': 3,
     'MK06': 4,
     'MK07': 5,
     'MK08': 6,
     'MK09': 7,
     'MK10': 8,
     'MK11': 9,
     'MK12': 10,
     'MK13': 11,
     'MK14': 12,
     'MK15': 13,
     'MK16': 14,
     'MK17': 15,
     'MK18': 16,
     'MK19': 17,
     'MK21': 18},
    'label': {'MK01': 'MK01 Uusimaa',
     'MK02': 'MK02 Southwest Finland',
     'MK04': 'MK04 Satakunta',
     'MK05': 'MK05 Kanta-Häme',
     'MK06': 'MK06 Pirkanmaa',
     'MK07': 'MK07 Päijät-Häme',
     'MK08': 'MK08 Kymenlaakso',
     'MK09': 'MK09 South Karelia',
     'MK10': 'MK10 South Savo',
     'MK11': 'MK11 North Savo',
     'MK12': 'MK12 North Karelia',
     'MK13': 'MK13 Central Finland',
     'MK14': 'MK14 South Ostrobothnia',
     'MK15': 'MK15 Ostrobothnia',
     'MK16': 'MK16 Central Ostrobothnia',
     'MK17': 'MK17 North Ostrobothnia',
     'MK18': 'MK18 Kainuu',
     'MK19': 'MK19 Lapland',
     'MK21': 'MK21 Åland'}},
   'link': {'describedby': [{'extension': {'Alue': 'SCALE-TYPE=nominal'}}]}},
  'Vuosi': {'extension': {'show': 'value'},
   'label': 'Year',
   'category': {'index': {'2016': 0,
     '2017': 1,
     '2018': 2,
     '2019': 3,
     '2020': 4},
    'label': {'2016': '2016',
     '2017': '2017',
     '2018': '2018',
     '2019': '2019',
     '2020': '2020'}},
   'link': {'describedby': [{'extension': {'Vuosi': 'SCALE-TYPE=None'}}]}},
  'Tiedot': {'extension': {'show': 'value'},
   'label': 'Information',
   'category': {'index': {'GDPcap': 0, 'EP': 1},
    'label': {'GDPcap': 'At current prices, euro', 'EP': 'Population'},
    'unit': {'GDPcap': {'base': 'euros', 'decimals': 1},
     'EP': {'base': 'henkilöä', 'decimals': 0}}}}},
 'value': [52146.9,
  1629277,
  53659.9,
  1646959,
  55083.8,
  1663324,
  56807.8,
  1680375,
  55537.6,
  1696202,
  36350.1,
  474933,
  38604.9,
  476610,
  39727.3,
  478130,
  40628.8,
  478962,
  39987.5,
  480372,
  35301.8,
  222349,
  36473.8,
  221069,
  37173.3,
  219511,
  36896.9,
  217688,
  37368.1,
  216084,
  32378.5,
  174246,
  33354,
  173251,
  33499,
  172042,
  34987,
  171145,
  35862.6,
  170751,
  36221.7,
  510045,
  37468.7,
  512988,
  39011.6,
  515833,
  40085.6,
  518603,
  40407.7,
  521362,
  31909.9,
  208550,
  32339.9,
  208311,
  33014.9,
  207721,
  33193,
  206855,
  33090.5,
  206043,
  35022.8,
  171274,
  37634.9,
  169731,
  40207.6,
  167657,
  41794.9,
  165540,
  41978.3,
  163634,
  36659.4,
  130831,
  39072.8,
  130186,
  39398.2,
  129311,
  39108.5,
  128257,
  37618.9,
  127339,
  30823.8,
  141022,
  31654.3,
  139622,
  32728.3,
  137648,
  33316.5,
  135394,
  33471.8,
  133508,
  32467.2,
  253027,
  34086.5,
  252193,
  35660.8,
  250992,
  36419.5,
  249709,
  36186.3,
  248634,
  30770.8,
  167964,
  31214.4,
  167020,
  33680.7,
  166005,
  33922,
  165017,
  33143.7,
  164001,
  33100.3,
  273678,
  34174.9,
  273845,
  35819.5,
  273531,
  36258.9,
  273091,
  35557.5,
  272758,
  30495.2,
  196972,
  32093.1,
  196078,
  32644.1,
  194950,
  34298.1,
  193762,
  34635.5,
  192679,
  38947.9,
  176812,
  39518.2,
  176501,
  40695.9,
  176233,
  41366.1,
  176058,
  40492.6,
  175870,
  34803.7,
  69030,
  37135.7,
  68904,
  38207.7,
  68609,
  38223,
  68298,
  38724.7,
  68073,
  33225.8,
  410602,
  34228.2,
  411503,
  34788.5,
  412009,
  36027.8,
  412496,
  36648.3,
  413330,
  28797.4,
  75064,
  31229.5,
  74381,
  33083.7,
  73510,
  33825.6,
  72684,
  34923.4,
  71985,
  36349.6,
  180533,
  38819.1,
  179715,
  38920.5,
  178873,
  38863,
  177842,
  39058.3,
  176913,
  47022.3,
  29099,
  47500.4,
  29352,
  43976.8,
  29639,
  45606.3,
  29837,
  40050,
  30007],
 'role': {'time': ['Vuosi'], 'metric': ['Tiedot']},
 'version': '2.0',
 'extension': {'px': {'tableid': 'statfin_altp_pxt_12bc', 'decimals': 0}}}

In [5]:
# save json_data to file
with open('../data/Indices/gdp_region_index.json', 'w') as outfile:
    json.dump(json_data, outfile)

In [7]:
values = json_data['value']
shape = json_data['size']

json_year = json_data['dimension']['Vuosi']['category']['label'].values()
json_region = json_data['dimension']['Alue']['category']['label'].values()
json_education = json_data['dimension']['Tiedot']['category']['label'].values()
print(json_year)
print(json_region)
print(json_education)
print(len(json_year))
print(len(json_region))
print(len(json_education))
print(shape)

# Load values into a 1D NumPy array
values = np.array(values).reshape(shape).squeeze()
# reshape = np.reshape(values, (19,12,6))
# print(reshape.shape)
# reshape
print(values.shape)
values

dict_values(['2016', '2017', '2018', '2019', '2020'])
dict_values(['MK01 Uusimaa', 'MK02 Southwest Finland', 'MK04 Satakunta', 'MK05 Kanta-Häme', 'MK06 Pirkanmaa', 'MK07 Päijät-Häme', 'MK08 Kymenlaakso', 'MK09 South Karelia', 'MK10 South Savo', 'MK11 North Savo', 'MK12 North Karelia', 'MK13 Central Finland', 'MK14 South Ostrobothnia', 'MK15 Ostrobothnia', 'MK16 Central Ostrobothnia', 'MK17 North Ostrobothnia', 'MK18 Kainuu', 'MK19 Lapland', 'MK21 Åland'])
dict_values(['At current prices, euro', 'Population'])
5
19
2
[19, 5, 2]
(19, 5, 2)

array([[[  52146.9, 1629277. ],
        [  53659.9, 1646959. ],
        [  55083.8, 1663324. ],
        [  56807.8, 1680375. ],
        [  55537.6, 1696202. ]],

       [[  36350.1,  474933. ],
        [  38604.9,  476610. ],
        [  39727.3,  478130. ],
        [  40628.8,  478962. ],
        [  39987.5,  480372. ]],

       [[  35301.8,  222349. ],
        [  36473.8,  221069. ],
        [  37173.3,  219511. ],
        [  36896.9,  217688. ],
        [  37368.1,  216084. ]],

       [[  32378.5,  174246. ],
        [  33354. ,  173251. ],
        [  33499. ,  172042. ],
        [  34987. ,  171145. ],
        [  35862.6,  170751. ]],

       [[  36221.7,  510045. ],
        [  37468.7,  512988. ],
        [  39011.6,  515833. ],
        [  40085.6,  518603. ],
        [  40407.7,  521362. ]],

       [[  31909.9,  208550. ],
        [  32339.9,  208311. ],
        [  33014.9,  207721. ],
        [  33193. ,  206855. ],
        [  33090.5,  206043. ]],

       [[  35022.8,  171274. ],
        [  37634.9,  169731. ],
        [  40207.6,  167657. ],
        [  41794.9,  165540. ],
        [  41978.3,  163634. ]],

       [[  36659.4,  130831. ],
        [  39072.8,  130186. ],
        [  39398.2,  129311. ],
        [  39108.5,  128257. ],
        [  37618.9,  127339. ]],

       [[  30823.8,  141022. ],
        [  31654.3,  139622. ],
        [  32728.3,  137648. ],
        [  33316.5,  135394. ],
        [  33471.8,  133508. ]],

       [[  32467.2,  253027. ],
        [  34086.5,  252193. ],
        [  35660.8,  250992. ],
        [  36419.5,  249709. ],
        [  36186.3,  248634. ]],

       [[  30770.8,  167964. ],
        [  31214.4,  167020. ],
        [  33680.7,  166005. ],
        [  33922. ,  165017. ],
        [  33143.7,  164001. ]],

       [[  33100.3,  273678. ],
        [  34174.9,  273845. ],
        [  35819.5,  273531. ],
        [  36258.9,  273091. ],
        [  35557.5,  272758. ]],

       [[  30495.2,  196972. ],
        [  32093.1,  196078. ],
        [  32644.1,  194950. ],
        [  34298.1,  193762. ],
        [  34635.5,  192679. ]],

       [[  38947.9,  176812. ],
        [  39518.2,  176501. ],
        [  40695.9,  176233. ],
        [  41366.1,  176058. ],
        [  40492.6,  175870. ]],

       [[  34803.7,   69030. ],
        [  37135.7,   68904. ],
        [  38207.7,   68609. ],
        [  38223. ,   68298. ],
        [  38724.7,   68073. ]],

       [[  33225.8,  410602. ],
        [  34228.2,  411503. ],
        [  34788.5,  412009. ],
        [  36027.8,  412496. ],
        [  36648.3,  413330. ]],

       [[  28797.4,   75064. ],
        [  31229.5,   74381. ],
        [  33083.7,   73510. ],
        [  33825.6,   72684. ],
        [  34923.4,   71985. ]],

       [[  36349.6,  180533. ],
        [  38819.1,  179715. ],
        [  38920.5,  178873. ],
        [  38863. ,  177842. ],
        [  39058.3,  176913. ]],

       [[  47022.3,   29099. ],
        [  47500.4,   29352. ],
        [  43976.8,   29639. ],
        [  45606.3,   29837. ],
        [  40050. ,   30007. ]]])

In [24]:
# Create the nested index
tuples = []
for region in json_region:
    for year in json_year:
        tuples.append((region, year))

index = pd.MultiIndex.from_tuples(tuples, names=["Region", "Year"])

# Create a NumPy array from the value list
value_array = np.array(json_data['value'])
shape = json_data['size']

transformed_array = np.array(value_array).reshape(shape).squeeze()
# reshape from (5, 19, 12, 4) to (5*19*12, 4)
transformed_array = transformed_array.reshape(-1, len(json_education))

# Create a DataFrame from the value list with the nested index
df = pd.DataFrame(data=transformed_array, index=index, columns=json_education)

# Print the DataFrame
df

                   At current prices, euro  Population
Region       Year
MK01 Uusimaa 2016                  52146.9   1629277.0
             2017                  53659.9   1646959.0
             2018                  55083.8   1663324.0
             2019                  56807.8   1680375.0
             2020                  55537.6   1696202.0
...                                    ...         ...
MK21 Åland   2016                  47022.3     29099.0
             2017                  47500.4     29352.0
             2018                  43976.8     29639.0
             2019                  45606.3     29837.0
             2020                  40050.0     30007.0

[95 rows x 2 columns]

In [25]:
df.reset_index(inplace=True)
df['Region code'] = df['Region'].str[:4]
df.rename(columns={'At current prices, euro': 'GDP per capita (EUR)'}, inplace=True)

df['GDP (EUR)'] = df['GDP per capita (EUR)'] * df['Population']

for col in ['GDP (EUR)', 'GDP per capita (EUR)']:
    # Calculate the difference between consecutive years for columns
    df[f'{col[:-5]} absolute growth (EUR)'] = df.groupby('Region')[col].diff()

    # Calculate the relative growth for columns
    df[f'{col[:-5]} relative growth (%)'] = df[f'{col[:-5]} absolute growth (EUR)'] / df[col] * 100

df.drop(columns=['Region'], inplace=True)
df

,Year,GDP per capita (EUR),Population,Region code,GDP (EUR),GDP absolute growth (EUR),GDP relative growth (%),GDP per capita absolute growth (EUR),GDP per capita relative growth (%)
0,2016,52146.9,1629277.0,MK01,8.496174e+10,NaN,NaN,NaN,NaN
1,2017,53659.9,1646959.0,MK01,8.837566e+10,3.413910e+09,3.862953,1513.0,2.819610
2,2018,55083.8,1663324.0,MK01,9.162221e+10,3.246551e+09,3.543411,1423.9,2.584971
3,2019,56807.8,1680375.0,MK01,9.545841e+10,3.836200e+09,4.018714,1724.0,3.034795
4,2020,55537.6,1696202.0,MK01,9.420299e+10,-1.255419e+09,-1.332674,-1270.2,-2.287099
...,...,...,...,...,...,...,...,...,...
90,2016,47022.3,29099.0,MK21,1.368302e+09,NaN,NaN,NaN,NaN
91,2017,47500.4,29352.0,MK21,1.394232e+09,2.592983e+07,1.859794,478.1,1.006518
92,2018,43976.8,29639.0,MK21,1.303428e+09,-9.080337e+07,-6.966502,-3523.6,-8.012407
93,2019,45606.3,29837.0,MK21,1.360755e+09,5.732680e+07,4.212866,1629.5,3.572971
94,2020,40050.0,30007.0,MK21,1.201780e+09,-1.589748e+08,-13.228276,-5556.3,-13.873408

In [26]:
final_df = pd.merge(base_df, df, on='Region code', how='left')
final_df

,Region code,Region name (en),Region name (fi),Year,GDP per capita (EUR),Population,GDP (EUR),GDP absolute growth (EUR),GDP relative growth (%),GDP per capita absolute growth (EUR),GDP per capita relative growth (%)
0,MK01,Uusimaa,Uusimaa,2016,52146.9,1629277.0,8.496174e+10,NaN,NaN,NaN,NaN
1,MK01,Uusimaa,Uusimaa,2017,53659.9,1646959.0,8.837566e+10,3.413910e+09,3.862953,1513.0,2.819610
2,MK01,Uusimaa,Uusimaa,2018,55083.8,1663324.0,9.162221e+10,3.246551e+09,3.543411,1423.9,2.584971
3,MK01,Uusimaa,Uusimaa,2019,56807.8,1680375.0,9.545841e+10,3.836200e+09,4.018714,1724.0,3.034795
4,MK01,Uusimaa,Uusimaa,2020,55537.6,1696202.0,9.420299e+10,-1.255419e+09,-1.332674,-1270.2,-2.287099
...,...,...,...,...,...,...,...,...,...,...,...
90,MK21,Åland,Ahvenanmaa,2016,47022.3,29099.0,1.368302e+09,NaN,NaN,NaN,NaN
91,MK21,Åland,Ahvenanmaa,2017,47500.4,29352.0,1.394232e+09,2.592983e+07,1.859794,478.1,1.006518
92,MK21,Åland,Ahvenanmaa,2018,43976.8,29639.0,1.303428e+09,-9.080337e+07,-6.966502,-3523.6,-8.012407
93,MK21,Åland,Ahvenanmaa,2019,45606.3,29837.0,1.360755e+09,5.732680e+07,4.212866,1629.5,3.572971
94,MK21,Åland,Ahvenanmaa,2020,40050.0,30007.0,1.201780e+09,-1.589748e+08,-13.228276,-5556.3,-13.873408

In [27]:
final_df.to_csv('./../data/Indices/gdp_region_index.csv', index=False)